# Installing packegs from nuage at compute nodes

#- hosts: "{{ cluster_name }}_node"
- hosts: "{{ cluster_name }}_controller"

  become: true

  tasks:

    - name: Update the default section of the neutron.conf
      lineinfile:
        dest: /etc/neutron/neutron.conf
        insertafter: '^\[DEFAULT\]'
        regexp: 'ovs_integration_bridge'
        line: "ovs_integration_bridge = alubr0"
        state: present

    - name: Update the service provider section of the neutron.conf
      lineinfile:
        dest: /etc/neutron/neutron.conf
        insertafter: '^\[service_providers\]'
        regexp: 'service_provider'
        line: "service_provider=LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default"
        state: present

    - name: Update the default section of the lbaas_agent.ini 
      lineinfile:
        dest: /etc/neutron/lbaas_agent.ini 
        insertafter: '^\[DEFAULT\]'
        regexp: '{{ item.regexp }}'
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'ovs_use_veth' , line: 'ovs_use_veth=False' }
        - { regexp: 'interface_driver' , line: 'interface_driver=nuage_neutron.lbaas.agent.nuage_interface.NuageInterfaceDriver' }

    - name: Install some other packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - iputils
        - haproxy
   
    - name : restarting openvswitch
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - 'openvswitch'
        - 'neutron-lbaasv2-agent'
    
    - name: kill lbaasv1 process
      shell: kill `ps aux | grep -F 'neutron-lbaas-agent' | grep -v -F 'grep' | awk '{ print $2 }'` 
      ignore_errors: yes
