# moving some files to controller to run our playbook

- hosts: "{{ cluster_name }}_controller"

  become: true

  tasks:

    - name: check install notes
      command: tail -10 /root/install.log
      register: install_notes

    - debug: 
        var: install_notes.stdout_lines

    - name: check  credentials
      command: tail -10 /root/keystonerc_admin
      register: keystonerc_admin

    - debug: 
        var: keystonerc_admin.stdout_lines
    
